In [ ]:
!pip install numpy

In [ ]:
import numpy as np

In [ ]:
#ndarray


In [ ]:
python_list=[1,2,3,4,5]
print(python_list)


numpy_array=np.array([1,2,3,4,5])
print(numpy_array)

[1, 2, 3, 4, 5]
[1 2 3 4 5]


In [ ]:
#array-collection of elements

#bina array it take lot memory
marks1=23
marks=24
marks=34



In [ ]:
#1d array
#one dimensional array-list of num in single array


ar_1d=np.array([10,20,30,40,50])
print(ar_1d)


[10 20 30 40 50]


In [ ]:
#2d array
#2 dimenional array-row and col

ar_2d=np.array([[1,2,3],
               [4,5,6,],
               [7,8,9]])

print(ar_2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
#multi dime -3d,4d, etc

#matrix

import numpy as np

matrix=np.array([[2,4,6],[8,10,12]])
print(matrix)

[[ 2  4  6]
 [ 8 10 12]]


In [ ]:
#creating array from lists\
#np.array([ele1,ele2,ele3])


import numpy as np
arr=np.array([1,2,3,4])
print(arr)

[1 2 3 4]


In [ ]:
#with defaullu values
#np.zeros(shape)

import numpy as np
zeros_array=np.zeros(3)
print(zeros_array)

#ones
ones_array=np.ones((3,3))
print(ones_array)

[0. 0. 0.]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
#full(shape,value)

import numpy as np

filled_array=np.full((2,3),7)
print(filled_array)

[[7 7 7]
 [7 7 7]]


In [ ]:
#creating sequ of number in numpy


#arrange()

#arrange(start,stop,end)

import numpy as np
arr=np.arange(1,10,2)
print(arr)

[1 3 5 7 9]


In [ ]:
#creating identity matrices

import numpy as np
identity_matices=np.eye(5)
print(identity_matices)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
#operations in numpy

#numpy properties
#shape,size,type
#no of dimensions

#warehouse manager->har product ka name,quantity,price

#product-data,shape,type


In [ ]:
#when working with multi dimensional data it helps(shape)

import numpy as np

arr_2s=np.array([[1,2,3],[4,5,6]])
print(arr_2s.shape)#roe,col

(2, 3)


In [ ]:
#size-totaal no elements in array

arr=np.array([[110,20,30],[50,69,50]])
print(arr.size)

6


In [ ]:
#ndim->kitne num dimensions

#array.ndim

arr_1d=np.array([1,2,3])

arr_2d=np.array([[1,2,3],[4,5,6]])


print(arr_1d.ndim)
print(arr_2d.ndim)

1
2


In [ ]:
#dtype
#data type of elements

arr=np.array([10,20,30,5,40])
print(arr.dtype)

int64


In [ ]:
#astype

#data type changing

import numpy as np

arr=np.array([1.2,2.5,3.8])
print(arr.dtype)

int_arr=arr.astype(int)
print(int_arr)
print(int_arr.dtype)


float64
[1 2 3]
int64


In [ ]:
#mathematical opeartion

import numpy as np

arr=np.array([10,20,30])

print(arr+5)
print(arr*2)
print(arr**2)

[15 25 35]
[20 40 60]
[100 400 900]


In [ ]:
#aggregation function(summarise)
#np.sum(array)
#np.mean(array)
#np.min(arr)
#np.max(arr)
#np.std(array)
#np.var(arr)

In [ ]:
import numpy as np
arr=np.array([10,20,30,40,50])

print(np.sum(arr))
print(np.mean(arr))
print(np.max(arr))
print(np.std(arr))
print(np.var(arr))

150
30.0
50
14.142135623730951
200.0


In [ ]:
#indexing and slicing
#FANCY INDEXING
#BOOLEAN MASKING


In [ ]:
#INDEXING AND SLICING
#ACCES.PY

import numpy as np

"""
array[index] #1d array

array[row,columns]#2d"""

arr=np.array([10,20,30,40,50])

print(arr[0])
print(arr[2])
print(arr[-1])


#slicing
"array[start:stop:end]"
"arr[start:end]"
"negative step -1 reverse"

import numpy as np
arr=np.array([10,20,30,40,50])
print(arr[1:5]) #index 1 to 4

print(arr[:4])

print(arr[::2])

print(arr[::-1])

10
30
50
[20 30 40 50]
[10 20 30 40]
[10 30 50]
[50 40 30 20 10]


In [ ]:
arr=np.array([10,20,30,40,50,60]) #SELECTING MULTIPLE ELEMENTS AT TIME PASS AS LIST

print(arr[[0,2,4]]) #PASS AS LIST

[10 30 50]


In [ ]:
#FILTERING DATA-BOOLEAN MASKING BASED OM CONDTION

# arr=np.array([10,20,30,40,50,60])
# print(arr[arr>25])


#reshaping(manipulating)
"""reshape(rows,columns)
if dimensions are mentioned
"""

#reshaping return view it not create new copy


import numpy as np
ar=np.array([1,2,3,4,5,6])
reshaped_arr=ar.reshape(2,3)
print(reshaped_arr)


#flattening-multi dim to 1d array

#.ravel->returns view
#flatten->return copy

arr_2d=np.array([[1,2,3],[4,5,6]])
print(arr_2d.ravel())
print(arr_2d.flatten())



"""indexing,sloicng,fancy indexing,array shape,ravel,flatten"""

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]
[1 2 3 4 5 6]


In [ ]:
#advanced topics

#add
#remove
#stack
#split


"""
np.inset(array,index,value,axis=None)
array-original array
index-
value-
axis
axis =-,row wise
1 columns wise
"""

import numpy as np
arr=np.array([10,20,30,40,50,60])
print(arr)

new_arr=np.insert(arr,2,100,axis=0)

print(new_arr)


#insert in 2d array

arr_2d=np.array([[1,2],[3,4]])

new_arr_2d=np.insert(arr_2d,1,[5,6],axis=0)
print(new_arr_2d)


#append last

arr=np.array([10,20,30,40,50,60])

print(arr)

new_arr=np.append(arr,[40,50,60])

print(new_arr)



#concatenate
""" np.concatenate(array1,array2),axis=0

axis 0->vertical

axis 1>horizontal
"""

import numpy as np

arr1=np.array([1,2,3])
arr2=np.array([4,5,6])

new_arr=np.concatenate((arr1,arr2))
print(new_arr)



#removing elemnt
""" np.delete(array,index,axis=none)
flatten array
"""

arr=np.array([10,20,30,40,50,60])
print(arr)

new_arr=np.delete(arr,0)
print(new_arr)




#2d array -remove

import numpy as np
arr_2d=np.array([[1,2,3],[4,5,6]])

new_arr_2d=np.delete(arr_2d,0,axis=0)
print(new_arr_2d)

[10 20 30 40 50 60]
[ 10  20 100  30  40  50  60]
[[1 2]
 [5 6]
 [3 4]]
[10 20 30 40 50 60]
[10 20 30 40 50 60 40 50 60]
[1 2 3 4 5 6]
[10 20 30 40 50 60]
[20 30 40 50 60]
[[4 5 6]]


In [ ]:
"""stacking ->vertically->vstack() row wise
hstack column wise"""

import numpy as np
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])

print(np.vstack([arr1,arr2]))
print(np.hstack([arr1,arr2]))



#splitting
"""
np.split()
equal
np.hsplit()
np.vsplit()
"""


arr=np.array([10,20,30,40,50,60])

print(np.split(arr,2))




#vetorization

#broadcasting-->
prices=[100,200,300]

discount=10 #10% DISCOUNT

final_prices=[]

for price in prices:
  final_price=price-(price*discount/100)

  final_prices.append(final_price)
print(final_price)


#by using brodcasting


import numpy as np

prices=np.array([100,200,300])

discount=10

final_prices=prices-(prices*discount/100)

print(final_prices)

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]
[array([10, 20, 30]), array([40, 50, 60])]
270.0
[ 90. 180. 270.]


In [ ]:
#how numpy hnalde diff diffe shapes arrays

#1.matching dimensions [1,2,3],[3,4,5] =>+ easy
#2.expandinf single elements [1,2,3]+10=>[11,12,13]

#3.incompatble

arr=np.array([100,200,300])
result=arr*2
print(result)


matrix=np.array([[1,2,3],[4,5,6]])

vector=np.array([10,20,30])

result=matrix+vector

print(result)



#arr1=np.array([[1,2,3],[4,5,6])
#arr2=np.array([1,2])

# res=arr1+arr2
# print(res)

[200 400 600]
[[11 22 33]
 [14 25 36]]
[5 7 9]


In [ ]:
list1=[1,2,3]
list2=[4,5,6]

# result=[x+y for x,y in zip(list1,list2)]

arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
result=arr1+arr2
print(result)



#mul
arr=np.array([10,20,30])
mul=arr*3
print(mul)

[5 7 9]
[30 60 90]


In [ ]:
#broadcasting->samll array to big arrays,speed -faster then array,#1d o 2d

#vectorizatio
#1.faster then loop
#2.entire loop

#matrix operations



In [ ]:
#missing value handling
#1.np.isnan
#2.np.nan_to_num()
#3.np.isinf()




In [ ]:
#nan -not a number

arr1=np.array([1,2,np.nan,4,np.nan,6])

print(arr1)

print(np.isnan(arr1))


#print(np.nan == np.nan) #no we can not compare directly

#isnan
#np.nan_to_num(array,nan=value) default -0

arr=np.array([1,2,np.nan,4,np.nan,6])

cleaned_arr=np.nan_to_num(arr,nan=100)

print(cleaned_arr)


#infinite

#np.isinf(arr) 10*100

#1/0

arr2=np.array([1,2,np.inf,4,-np.inf,6])

print(np.isinf(arr2))



#replace

cleaned_arr2=np.nan_to_num(arr2,posinf=1000,neginf=1000)

print(cleaned_arr2)





[ 1.  2. nan  4. nan  6.]
[False False  True False  True False]
[  1.   2. 100.   4. 100.   6.]
[False False  True False  True False]
[   1.    2. 1000.    4. 1000.    6.]


In [ ]:
#projects

